name: ğŸ·ï¸ ç‰ˆæœ¬å‘å¸ƒ

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    permissions:
      contents: write

    steps:
      - name: ğŸ” æ£€å‡ºæºä»£ç 
        uses: actions/checkout@v6

      - name: ğŸšœ å®‰è£… uv
        uses: astral-sh/setup-uv@v7

      - name: ğŸ”¨ åŒæ­¥ä¾èµ–
        run: uv sync

      - name: ğŸ“¦ æ‰“åŒ…å¹¶å‹ç¼©
        run: uv run pack.py

      - name: ğŸ“¢ å‘å¸ƒåˆ° Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: dist/hterm-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}